### ISSUE TITLE
Install files into a more distinctive directory

### ISSUE THREAD

**Issue by jayvdb** [hsorby/exclude_until_coverage_plugin#1]
```
$ sudo python3.7 -m pip install .
...
$ ls /home/python3.7/lib/python3.7/site-packages/coverage_plugin/
exclude_until.py  __init__.py  __pycache__
```
"coverage_plugin" is not descriptive of which plugin it is.

It should be possible to tell setuptools to create a new directory name when it installs the files, even without renaming the directories in git.

However as `coverage` plugin registration is putting the module name into the config file, I suspect that the change of installation directory will require a change to any previous usage of this plugin.  If that is a problem, a backwards compatible shim is needed for the old name.

**Comment by hsorby** [comment]
I'm open to suggestions for another name.

**Comment by jayvdb** [comment]
I'll throw in the very boring directory name `exclude_until_coverage_plugin` :P

**Comment by hsorby** [comment]
Non-backwards compatible change made in [release 0.2.1](https://pypi.org/project/exclude-until-coverage-plugin/) to `exclude_until_coverage_plugin`.  This version only works with coverage < 5.0.  No shim provided, apologies for any pain this may cause.
